apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "servicecomposer.fullname" . }}-config
  labels:
    {{- include "servicecomposer.labels" . | nindent 4 }}
data:
  DJANGO_DEBUG: {{ .Values.config.debug | quote }}
  DJANGO_LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  DB_ENGINE: {{ .Values.config.dbEngine | quote }}
  DB_HOST: {{ include "servicecomposer.postgresql.fullname" . }}
  DB_PORT: {{ .Values.config.dbPort | quote }}
  DB_NAME: {{ .Values.config.dbName | quote }}
