postgresql:
  enabled: true
  auth:
    username: viosuser
    password: viospassword
    database: portal

config:
  replicaCount: 1
  appPort: 5000
  type: NodePort
  extAppPort: 30010
  systemEnv: KUBERNETES
  livenessPath: /liveness
  readinessPath: /readiness
  readinessFailureThreshold: 5
  readinessPeriodSeconds: 5
  portalDev: UoB

image:
  repository: digicatapult/vios-portal
  pullPolicy: Always
  tag: 0.1.12

  command: ['./start.sh']

serviceAccount:
  create: false
  annotations: {}
  name: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
