apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "portal.fullname" . }}-config
  labels:
    {{- include "portal.labels" . | nindent 4 }}
data:
  DB_HOST: {{ include "portal.postgresql.fullname" . }}
  POSTGRES_DB: {{ .Values.postgresql.auth.database | quote }}
  PORTAL_DEV: {{ .Values.config.portalDev | quote }}
