postgresql:
  enabled: true
  auth:
    username: sbuser
    password: sbpassword
    database: servicebroker

config:
  replicaCount: 1
  appPort: 8000
  type: NodePort
  nodePort: 31967
  debug: "True"
  logLevel: DEBUG
  smaHost: servicemanager
  smaPort: 8000
  agaHost: apigateway
  agaPort: 8000
  icmHost: connectivitymanager
  icmPort: 8000
  repHost: repository
  repPort: 8000
  mobHost: mobilitymanager
  mobPort: 8000

image:
  repository: digicatapult/vios-servicebroker
  pullPolicy: Always
  tag: 0.1.3

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

serviceAccount:
  create: false
  annotations: {}
  name: ""
