postgresql:
  enabled: true
  auth:
    username: viosuser
    password: viospassword
    database: apigateway

config:
  replicaCount: 1
  appPort: 8000
  type: NodePort
  nodePort: 30007
  debug: "True"
  logLevel: DEBUG
  sbrHost: servicebroker
  sbrPort: 8000
  icmHost: connectivitymanager
  icmPort: 8000
  proHost: profiler
  proPort: 8000
  monHost: monitor
  monPort: 8000
  mobHost: mobilitymanager
  mobPort: 8000

image:
  repository: digicatapult/vios-apigateway
  pullPolicy: Always
  tag: 0.1.4

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

serviceAccount:
  create: false
  annotations: {}
  name: ""
