apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "servicemanager.fullname" . }}-config
  labels:
    {{- include "servicemanager.labels" . | nindent 4 }}
data:
  APP_DEBUG: {{ .Values.config.debug | quote }}
  APP_LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  POSTGRES_HOST: {{ include "servicemanager.postgresql.fullname" . }}
  POSTGRES_DB: {{ .Values.postgresql.auth.database | quote }}
  VIOS_SERVICE_BROKER_HOST: {{ .Values.config.sbrHost | quote }}
  VIOS_SERVICE_BROKER_PORT: {{ .Values.config.sbrPort | quote }}
  VIOS_SERVICE_COMPOSER_HOST: {{ .Values.config.scoHost | quote }}
  VIOS_SERVICE_COMPOSER_PORT: {{ .Values.config.scoPort | quote }}
  VIOS_CONNECTIVITY_MANAGER_HOST: {{ .Values.config.icmHost | quote }}
  VIOS_CONNECTIVITY_MANAGER_PORT: {{ .Values.config.icmPort | quote }}
  VIOS_PROFILER_HOST: {{ .Values.config.proHost | quote }}
  VIOS_PROFILER_PORT: {{ .Values.config.proPort | quote }}
