{{- $fullName := include "servicemanager.fullname" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "servicemanager.labels" . | nindent 4 }}
spec:
  type: {{ .Values.config.type }}
  ports:
    - port: {{ .Values.config.appPort }}
      targetPort: {{ .Values.config.appPort }}
      nodePort: {{ .Values.config.nodePort }}
      protocol: TCP
      name: http
  selector:
    name: {{ include "servicemanager.fullname" . }}-app
