postgresql:
  enabled: true
  auth:
    username: viosuser
    password: viospassword
    database: servicemanager

config:
  replicaCount: 1
  appPort: 8000
  type: NodePort
  nodePort: 30313
  debug: "True"
  logLevel: DEBUG
  sbrHost: servicebroker
  sbrPort: 8000
  scoHost: servicecomposer
  scoPort: 8000
  icmHost: connectivitymanager
  icmPort: 8000
  proHost: profiler
  proPort: 8000

image:
  repository: digicatapult/vios-servicemanager
  pullPolicy: Always
  tag: 0.1.14

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

serviceAccount:
  create: false
  annotations: {}
  name: ""
