{{- $fullName := include "portalfilestorage.fullname" . -}}
kind: Service
apiVersion: v1
metadata:
  name: {{ $fullName }}
  labels:
  	{{- include "portalfilestorage.labels" . | nindent 4 }}
spec:
  type: {{ .Values.config.type }}
  ports:
    - port: {{ .Values.config.appPort }}
      # Port to forward to inside the pod
      protocol: TCP
      name: http
      # Port to forward to inside the pod
      targetPort: {{ .Values.config.appPort }}
      # Port accessible outside cluster
      nodePort: {{ .Values.config.extAppPort }}
  selector:
    name: {{ $fullName }}-app
