apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "portalfilestorage.fullname" . }}-config
  labels:
    {{- include "portalfilestorage.labels" . | nindent 4 }}
data:
  DB_ENGINE: {{ .Values.config.dbEngine | quote }}
  DB_HOST: {{ include "portalfilestorage.postgresql.fullname" . }}
  DB_PORT: {{ .Values.config.dbPort | quote }}
  DB_NAME: {{ .Values.config.dbName | quote }}
