apiVersion: v1
kind: Secret
metadata:
  name: {{ include "portalfilestorage.fullname" . }}-secret
  labels:
    {{- include "portalfilestorage.labels" . | nindent 4 }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.postgresql.auth.password | b64enc | quote }}
  DB_USERNAME: {{ .Values.postgresql.auth.username | b64enc | quote }}
