apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "portalfilestorage.fullname" . }}-app
  labels:
    {{- include "portalfilestorage.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.config.replicaCount }}
  selector:
    matchLabels:
      name: {{ include "portalfilestorage.fullname" . }}-app
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/portalfilestorage-configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/portalfilestorage-secrets.yaml") . | sha256sum }}
      labels:
        name: {{ include "portalfilestorage.fullname" . }}-app
    spec:
      initContainers:
        - name: {{ include "portalfilestorage.fullname" . }}-init
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          command: ['python', 'manage.py', 'makemigrations']
          envFrom:
          - configMapRef:
              name: {{ include "portalfilestorage.fullname" . }}-config
          - secretRef:
              name: {{ include "portalfilestorage.fullname" . }}-secret
      containers:
        - name: {{ include "portalfilestorage.fullname" . }}-app
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          command: {{ .Values.image.command }}
          ports:
             - containerPort: {{ .Values.config.appPort }}
          envFrom:
          - configMapRef:
              name: {{ include "portalfilestorage.fullname" . }}-config
          - secretRef:
              name: {{ include "portalfilestorage.fullname" . }}-secret
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP 
      {{- include "portalfilestorage.imagePullSecrets" . | indent 6 }}
      restartPolicy: Always
