apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mobilitymanager.fullname" . }}-config
  labels:
    {{- include "mobilitymanager.labels" . | nindent 4 }}
data:
  APP_DEBUG: {{ .Values.config.debug | quote }}
  APP_LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  POSTGRES_DB: {{ .Values.postgresql.auth.database | quote }}
  POSTGRES_HOST: {{ include "mobilitymanager.postgresql.fullname" . }}
  VIOS_SERVICE_MANAGER_HOST: {{ .Values.config.smaHost | quote }}
  VIOS_SERVICE_MANAGER_PORT: {{ .Values.config.smaPort | quote }}
  VIOS_API_GATEWAY_HOST: {{ .Values.config.agaHost | quote }}
  VIOS_API_GATEWAY_PORT: {{ .Values.config.agaPort | quote }}
  VIOS_SERVICE_BROKER_HOST: {{ .Values.config.sbrHost | quote }}
  VIOS_SERVICE_BROKER_PORT: {{ .Values.config.sbrPort | quote }}
  VIOS_REPOSITORY_HOST: {{ .Values.config.repHost | quote }}
  VIOS_REPOSITORY_PORT: {{ .Values.config.repPort | quote }}
  VIOS_SERVICE_COMPOSER_HOST: {{ .Values.config.scoHost | quote }}
  VIOS_SERVICE_COMPOSER_PORT: {{ .Values.config.scoPort | quote }}
