apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "profiler.fullname" . }}-config
  labels:
    {{- include "profiler.labels" . | nindent 4 }}
data:
  APP_DEBUG: {{ .Values.config.debug | quote }}
  APP_LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  POSTGRES_HOST: {{ include "profiler.postgresql.fullname" . }}
  POSTGRES_DB: {{ .Values.postgresql.auth.database | quote }}
  VIOS_SERVICE_MANAGER_HOST: {{ .Values.config.smaHost | quote }}
  VIOS_SERVICE_MANAGER_PORT: {{ .Values.config.smaPort | quote }}
  VIOS_MONITORING_HOST: {{ .Values.config.monHost | quote }}
  VIOS_MONITORING_PORT: {{ .Values.config.monPort | quote }}
