apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "apigateway.fullname" . }}-config
  labels:
    {{- include "apigateway.labels" . | nindent 4 }}
data:
  APP_DEBUG: {{ .Values.config.debug | quote }}
  APP_LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  POSTGRES_HOST: {{ include "apigateway.postgresql.fullname" . }}
  POSTGRES_DB: {{ .Values.postgresql.auth.database | quote }}
  VIOS_SERVICE_BROKER_HOST: {{ .Values.config.sbrHost | quote }}
  VIOS_SERVICE_BROKER_PORT: {{ .Values.config.sbrPort | quote }}
  VIOS_CONNECTIVITY_MANAGER_HOST: {{ .Values.config.icmHost | quote }}
  VIOS_CONNECTIVITY_MANAGER_PORT: {{ .Values.config.icmPort | quote }}
  VIOS_PRO_HOST: {{ .Values.config.proHost | quote }}
  VIOS_PRO_PORT: {{ .Values.config.proPort | quote }}
  VIOS_MOBILITY_MANAGER_HOST: {{ .Values.config.mobHost | quote }}
  VIOS_MOBILITY_MANAGER_PORT: {{ .Values.config.mobPort | quote }}
  VIOS_MON_HOST: {{ .Values.config.monHost | quote }}
  VIOS_MON_PORT: {{ .Values.config.monPort | quote }}
