apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "repository.fullname" . }}-celery
  labels:
    {{- include "repository.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.config.replicaCount }}
  selector:
    matchLabels:
      name: {{ include "repository.fullname" . }}-celery
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/rep-configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/rep-secrets.yaml") . | sha256sum }}
      labels:
        name: {{ include "repository.fullname" . }}-celery
    spec:
      {{- include "repository.imagePullSecrets" . | indent 6 }}
      containers:
        - name: {{ include "repository.fullname" . }}-celery
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          command: ['celery', '-A', 'config', 'worker', '-l', 'INFO', '-c', '10', '-Ofair', '--without-gossip', '--without-mingle', '--without-heartbeat']
          envFrom:
          - configMapRef:
              name: {{ include "repository.fullname" . }}-config
          - secretRef:
              name: {{ include "repository.fullname" . }}-secret
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
