postgresql:
  enabled: true
  auth:
    username: viosuser
    password: viospassword
    database: mobilitymanager

config:
  replicaCount: 1
  appPort: 8000
  type: NodePort
  nodePort: 30500
  debug: "True"
  logLevel: DEBUG
  smaHost: servicemanager
  smaPort: 8000
  agaHost: apigateway
  agaPort: 8000
  scoHost: servicecomposer
  scoPort: 8000
  repHost: repository
  repPort: 8000
  sbrHost: servicebroker
  sbrPort: 8000

image:
  repository: digicatapult/vios-mobilitymanager
  pullPolicy: Always
  tag: 0.1.3

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

serviceAccount:
  create: false
  annotations: {}
  name: ""
