postgresql:
  enabled: true
  auth:
    username: viosuser
    password: viospassword
    database: edgeproxy

config:
  replicaCount: 1
  appPort: 8000
  type: NodePort
  extAppPort: 30001
  dbPort: 5432
  debug: "True"
  logLevel: DEBUG
  vlanStart: tbc
  vlanEnd: tbc
  openstackServer: tbc
  openstackUser: tbc
  openstackPassword: tbc
  openstackDomain: default
  openstackProject: tbc
  openstackNetworkType: vlan
  openstackNetworkProvider: tbc
  openstackMgmtNetwork: tbc
  openstackUoBDns: ""
  vyosServer: tbc
  vyosEthernetPort: eth0
  vyosInstanceName: tbc
  vyosKey: demo_key
  osmVersion: tbc
  osmServer: tbc
  osmUsername: admin
  osmPasswd: admin
  osmProject: admin
  apigatewayHost: tbc
  apigatewayPort: 30007
  vimAccount: tbc
  netosAddr: tbc
  netosCertPath: "False"
  netosUser: admin
  netosPassword: admin
  appEndpoint: api/application/
  epaServerIp: tbc
  dnsServerIp: tbc
  dnsServerPort: 80
  i2SmIp: tbc
  i2SmPort: 30989

image:
  repository: digicatapult/vios-edgeproxy
  pullPolicy: Always
  tag: 0.1.1

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

serviceAccount:
  create: false
  annotations: {}
  name: ""

ingress:
  enabled: false
