postgresql:
  enabled: true
  auth:
    username: viosuser
    password: viospassword
    database: profiler

config:
  replicaCount: 1
  appPort: 8000
  type: NodePort
  nodePort: 32338
  debug: "True"
  logLevel: DEBUG
  systemEnv: KUBERNETES
  smaHost: servicemanager
  smaPort: 8000
  monHost: monitoring
  monPort: 8000

image:
  repository: digicatapult/vios-profiling
  pullPolicy: Always
  tag: 0.1.2

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

serviceAccount:
  create: false
  annotations: {}
  name: ""
