apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "edgeproxy.fullname" . }}-app
  labels:
    {{- include "edgeproxy.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.config.replicaCount }}
  selector:
    matchLabels:
      name: {{ include "edgeproxy.fullname" . }}-app
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
      labels:
        name: {{ include "edgeproxy.fullname" . }}-app
    spec:
      {{- include "edgeproxy.imagePullSecrets" . | indent 6 }}
      initContainers:
        - name: {{ include "edgeproxy.fullname" . }}-init
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          command: ['sleep', '60']
      containers:
        - name: {{ include "edgeproxy.fullname" . }}-app
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.config.appPort }}
          envFrom:
          - configMapRef:
              name: {{ include "edgeproxy.fullname" . }}-config
          - secretRef:
              name: {{ include "edgeproxy.fullname" . }}-secret
#          livenessProbe:
#            httpGet:
#              path: /
#              port: http
#          readinessProbe:
#            httpGet:
#              path: /
#              port: http

