apiVersion: v1
kind: Secret
metadata:
  name: {{ include "monitoring.fullname" . }}-secret
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
type: Opaque
data:
  MONGO_PASSWORD: {{ .Values.mongodb.auth.password | b64enc | quote }}
  MONGO_USER: {{ .Values.mongodb.auth.username | b64enc | quote }}
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.mongodb.auth.username | b64enc | quote }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.mongodb.auth.password | b64enc | quote }}
