apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "monitoring.fullname" . }}-config
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
data:
  MONGO_DEBUG: {{ .Values.config.debug | quote }}
  MONGO_HOST: {{ include "monitoring.mongodb.fullname" . }}
  MONGO_PORT: {{ .Values.config.dbPort | quote }}
  MONGO_DB_NAME: {{ .Values.mongodb.auth.database | quote }}
  MONGO_INITDB_DATABASE: {{ .Values.mongodb.auth.database | quote }}
  APIGATEWAY_HOST: {{ .Values.config.agaHost | quote }}
  APIGATEWAY_PORT: {{ .Values.config.agaPort | quote }}
  SYSTEM_ENV: {{ .Values.config.systemEnv | quote }}
