apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "servicebroker.fullname" . }}-config
  labels:
    {{- include "servicebroker.labels" . | nindent 4 }}
data:
  APP_DEBUG: {{ .Values.config.debug | quote }}
  APP_LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  POSTGRES_HOST: {{ include "servicebroker.postgresql.fullname" . }}
  POSTGRES_DB: {{ .Values.postgresql.auth.database | quote }}
  VIOS_SERVICE_MANAGER_HOST: {{ .Values.config.smaHost | quote }}
  VIOS_SERVICE_MANAGER_PORT: {{ .Values.config.smaPort | quote }}
  VIOS_API_GATEWAY_HOST: {{ .Values.config.agaHost | quote }}
  VIOS_API_GATEWAY_PORT: {{ .Values.config.agaPort | quote }}
  VIOS_CONNECTIVITY_MANAGER_HOST: {{ .Values.config.icmHost | quote }}
  VIOS_CONNECTIVITY_MANAGER_PORT: {{ .Values.config.icmPort | quote }}
  VIOS_REPOSITORY_HOST: {{ .Values.config.repHost | quote }}
  VIOS_REPOSITORY_PORT: {{ .Values.config.repPort | quote }}
  VIOS_MOBILITY_MANAGER_HOST: {{ .Values.config.mobHost | quote }}
  VIOS_MOBILITY_MANAGER_PORT: {{ .Values.config.mobPort | quote }}
